name: viva_development_compose
services:
  db:
    image: 'postgres:15.7'
    ports:
      - '5432:5432'
    networks:
      - viva_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=viva_development
      - TZ=America/Sao_Paulo # Get from .env file
      - PGTZ=America/Sao_Paulo # Get from .env file
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    stdin_open: true
    tty: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '8081:8081'
      - '8082:8082'
      - '8083:8083'
      - '5555:5555'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - viva_network
    environment:
      - CLIENTPARTNERPORT=8082
      - PLATFORMPARTNER=8083
      - MODERATORPARTNER=8081
      - DATABASE_URL=postgresql://postgres:password@db:5432/viva_development"

volumes:
  postgres: {}

networks:
  viva_network:
    driver: bridge
