name: viva_testing_compose

services:
  testdb:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=viva_test
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/via_test?schema=public"
    ports:
      - '5432:5432'